In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns

In [3]:
df = pd.read_csv('Dataset_spine.csv')
df = df.drop(['Unnamed: 13'], axis=1)
df.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,Class_att
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal

In [4]:
df.describe()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694,0.472979,21.321526,13.064511,11.933317,-14.053139,25.645981
std,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027,0.285787,8.639423,3.399713,2.893265,12.225582,10.450558
min,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179,0.003220,7.027000,7.037800,7.030600,-35.287375,7.007900
25%,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727,0.224367,13.054400,10.417800,9.541140,-24.289522,17.189075
50%,58.691038,16.357689,49.562398,42.404912,118.268178,11.767934,0.475989,21.907150,12.938450,11.953835,-14.622856,24.931950
75%,72.877696,22.120395,63.000000,52.695888,125.467674,41.287352,0.704846,28.954075,15.889525,14.371810,-3.497094,33.979600
max,129.834041,49.431864,125.742385,121.429566,163.071041,418.543082,0.998827,36.743900,19.324000,16.821080,6.972071,44.341200

In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
y = df['Class_att']
x = df.drop(['Class_att'], axis=1)

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.25, random_state=27)

In [16]:
clf = MLPClassifier(hidden_layer_sizes=(200,200,200), max_iter=500, alpha=0.0001,
                     solver='sgd', verbose=10,  random_state=21,tol=0.000000001)

In [17]:
clf.fit(x_train, y_train)

Iteration 1, loss = 3.67965173
Iteration 2, loss = 5.88892472
Iteration 3, loss = 1.78021156
Iteration 4, loss = 0.76365796
Iteration 5, loss = 0.76419320
Iteration 6, loss = 0.54834096
Iteration 7, loss = 0.76980771
Iteration 8, loss = 0.38437078
Iteration 9, loss = 0.36684531
Iteration 10, loss = 0.32133470
Iteration 11, loss = 0.40292786
Iteration 12, loss = 0.35760381
Iteration 13, loss = 0.35740589
Iteration 14, loss = 0.29148920
Iteration 15, loss = 0.29321331
Iteration 16, loss = 0.36032376
Iteration 17, loss = 0.33999789
Iteration 18, loss = 0.30133639
Iteration 19, loss = 0.28563113
Iteration 20, loss = 0.27750408
Iteration 21, loss = 0.30890010
Iteration 22, loss = 0.38517233
Iteration 23, loss = 0.27410996
Iteration 24, loss = 0.32500466
Iteration 25, loss = 0.32674774
Iteration 26, loss = 0.26724939
Iteration 27, loss = 0.26890141
Iteration 28, loss = 0.37527281
Iteration 29, loss = 0.28019489
Iteration 30, loss = 0.26625497
Iteration 31, loss = 0.26537001
Iteration 32, loss = 0.26309829
Iteration 33, loss = 0.26363773
Iteration 34, loss = 0.26291952
Iteration 35, loss = 0.25696301
Iteration 36, loss = 0.25752124
Iteration 37, loss = 0.25745154
Iteration 38, loss = 0.25505545
Iteration 39, loss = 0.26613289
Iteration 40, loss = 0.26733079
Iteration 41, loss = 0.25516668
Iteration 42, loss = 0.25111700
Iteration 43, loss = 0.25214781
Iteration 44, loss = 0.28021515
Iteration 45, loss = 0.39589542
Iteration 46, loss = 0.24792863
Iteration 47, loss = 0.27892964
Iteration 48, loss = 0.28741553
Iteration 49, loss = 0.28760111
Iteration 50, loss = 0.24405404
Iteration 51, loss = 0.24142555
Iteration 52, loss = 0.24857781
Iteration 53, loss = 0.28743242
Iteration 54, loss = 0.43242941
Iteration 55, loss = 0.25028546
Iteration 56, loss = 0.28283102
Iteration 57, loss = 0.27341208
Iteration 58, loss = 0.23900029
Iteration 59, loss = 0.24035019
Iteration 60, loss = 0.24364089
Iteration 61, loss = 0.27944821
Iteration 62, loss = 0.28330326
Iteration 63, loss = 0.23704562
Iteration 64, loss = 0.25141487
Iteration 65, loss = 0.28028405
Iteration 66, loss = 0.23352704
Iteration 67, loss = 0.32473510
Iteration 68, loss = 0.25107835
Iteration 69, loss = 0.24067593
Iteration 70, loss = 0.23410177
Iteration 71, loss = 0.26463096
Iteration 72, loss = 0.23208172
Iteration 73, loss = 0.24612756
Iteration 74, loss = 0.22773419
Iteration 75, loss = 0.27987066
Iteration 76, loss = 0.23186020
Iteration 77, loss = 0.23686928
Iteration 78, loss = 0.22532922
Iteration 79, loss = 0.27044582
Iteration 80, loss = 0.22619059
Iteration 81, loss = 0.22134508
Iteration 82, loss = 0.22585336
Iteration 83, loss = 0.22102073
Iteration 84, loss = 0.26190454
Iteration 85, loss = 0.28170892
Iteration 86, loss = 0.21895748
Iteration 87, loss = 0.22125936
Iteration 88, loss = 0.22481496
Iteration 89, loss = 0.24802554
Iteration 90, loss = 0.32166683
Iteration 91, loss = 0.22753331
Iteration 92, loss = 0.21406774
Iteration 93, loss = 0.21787313
Iteration 94, loss = 0.32346140
Iteration 95, loss = 0.22711471
Iteration 96, loss = 0.21183526
Iteration 97, loss = 0.21132489
Iteration 98, loss = 0.21140300
Iteration 99, loss = 0.23041360
Iteration 100, loss = 0.20888546
Iteration 101, loss = 0.21908501
Iteration 102, loss = 0.20923603
Iteration 103, loss = 0.21647435
Iteration 104, loss = 0.22103792
Iteration 105, loss = 0.20793832
Iteration 106, loss = 0.21581105
Iteration 107, loss = 0.21616743
Iteration 108, loss = 0.21508073
Iteration 109, loss = 0.23196295
Iteration 110, loss = 0.20924362
Iteration 111, loss = 0.22962271
Iteration 112, loss = 0.21248443
Iteration 113, loss = 0.21956499
Iteration 114, loss = 0.28906536
Iteration 115, loss = 0.20425086
Iteration 116, loss = 0.21496795
Iteration 117, loss = 0.21157366
Iteration 118, loss = 0.21067882
Iteration 119, loss = 0.31932758
Iteration 120, loss = 0.24685708
Iteration 121, loss = 0.21885386
Iteration 122, loss = 0.20732132
Iteration 123, loss = 0.20514576
Iteration 124, loss = 0.20164859
Iteration 125, loss = 0.22424977
Iteration 126, loss = 0.21449694
Iteration 127, loss = 0.23281487
Iteration 128, loss = 0.22026799
Iteration 129, loss = 0.23216879
Iteration 130, loss = 0.20193136
Iteration 131, loss = 0.20879771
Iteration 132, loss = 0.29468674
Iteration 133, loss = 0.25240104
Iteration 134, loss = 0.19636003
Iteration 135, loss = 0.19811574
Iteration 136, loss = 0.23125431
Iteration 137, loss = 0.21584847
Iteration 138, loss = 0.19518424
Iteration 139, loss = 0.19647021
Iteration 140, loss = 0.19262565
Iteration 141, loss = 0.19176241
Iteration 142, loss = 0.20665509
Iteration 143, loss = 0.18984999
Iteration 144, loss = 0.20486553
Iteration 145, loss = 0.20216519
Iteration 146, loss = 0.19419952
Iteration 147, loss = 0.22146632
Iteration 148, loss = 0.21204859
Iteration 149, loss = 0.27060470
Iteration 150, loss = 0.18753753
Iteration 151, loss = 0.21960059
Iteration 152, loss = 0.18658917
Iteration 153, loss = 0.19779113
Iteration 154, loss = 0.22037431
Iteration 155, loss = 0.19558015
Iteration 156, loss = 0.20740169
Iteration 157, loss = 0.21406970
Iteration 158, loss = 0.20676149
Iteration 159, loss = 0.18767653
Iteration 160, loss = 0.19081697
Iteration 161, loss = 0.20767274
Iteration 162, loss = 0.19264277
Iteration 163, loss = 0.20951158
Training loss did not improve more than tol=0.000000 for 10 consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 200, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=21, shuffle=True, solver='sgd', tol=1e-09,
       validation_fraction=0.1, verbose=10, warm_start=False)

In [18]:
y_pred = clf.predict(x_test)
accuracy_score(y_test, y_pred)

0.8205128205128205

In [12]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[45,  8],
       [ 7, 18]], dtype=int64)